try:
    a=4
except:
    print("ERROR FOUND ")
else:
    print("""Else statement runs when there is no exception found in the code \
or we say in try clause""")
    
